### ISSUE TITLE
a little bit gayer than lavaclient

### ISSUE THREAD

**Issue by luaugg** [arudiscord/andeclient#1]
this is unacceptable :/

**Comment by NotJustAnna** [comment]
instead of calling it "gay", you could instead be an adult and
1. PR help
2. comment out how WIP stuff can be implemented/enchanced/fixed

I'm doing andeclient because I want a solution which uses Java 11 HttpClient instead of yet another vert.x client and I want to benefit from Andesite features like Equalizer and Tremolo.

In fact, lavaclient is being used as my personal reference (together with Fred's Lavalink) for do's and don'ts, and you calling it "gayer than lavaclient" feels more like an insult than anything helpful at all.

You're welcome to contribute meaningful stuff to the library.
